version: '3.9'

services:
  testo-db:
    container_name: teslo-db
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
